export const GET_PRODUCTS = "GET_PRODUCTS";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const SORT_PRICE_ASCENDING = "SORT_PRICE_ASCENDING";
export const SORT_PRICE_DESCENDING = "SORT_PRICE_DESCENDING";
export const SORT_NAME_ASCENDING = "SORT_NAME_ASCENDING";
export const SORT_NAME_DESCENDING = "SORT_NAME_DESCENDING";
export const GET_RANGE = "GET_RANGE";
